// #pragma checksum "/Users/captainsafia/github.com/PictureFixer/PictureFixer/Client/Pages/Home/Index.razor" "{8829d00f-11b8-4213-878b-770e8597ac16}" "002b77ff4d4afd3f467b29b7f74bc48a2a149d21ac7deccdf8c5b67607b10e37"
// // <auto-generated/>
// #pragma warning disable 1591
// namespace PictureFixer.Client.Pages.Home
// {
//     #line hidden
//     using System;
//     using System.Collections.Generic;
//     using System.Linq;
//     using System.Threading.Tasks;
//     using Microsoft.AspNetCore.Components;
// #nullable restore
// #line 1 "/Users/captainsafia/github.com/PictureFixer/PictureFixer/Client/_Imports.razor"
// using System.Net.Http;

// #line default
// #line hidden
// #nullable disable
// #nullable restore
// #line 2 "/Users/captainsafia/github.com/PictureFixer/PictureFixer/Client/_Imports.razor"
// using System.Net.Http.Json;

// #line default
// #line hidden
// #nullable disable
// #nullable restore
// #line 3 "/Users/captainsafia/github.com/PictureFixer/PictureFixer/Client/_Imports.razor"
// using Microsoft.AspNetCore.Components.Forms;

// #line default
// #line hidden
// #nullable disable
// #nullable restore
// #line 4 "/Users/captainsafia/github.com/PictureFixer/PictureFixer/Client/_Imports.razor"
// using Microsoft.AspNetCore.Components.Routing;

// #line default
// #line hidden
// #nullable disable
// #nullable restore
// #line 5 "/Users/captainsafia/github.com/PictureFixer/PictureFixer/Client/_Imports.razor"
// using Microsoft.AspNetCore.Components.Web;

// #line default
// #line hidden
// #nullable disable
// #nullable restore
// #line 6 "/Users/captainsafia/github.com/PictureFixer/PictureFixer/Client/_Imports.razor"
// using Microsoft.AspNetCore.Components.Web.Virtualization;

// #line default
// #line hidden
// #nullable disable
// #nullable restore
// #line 7 "/Users/captainsafia/github.com/PictureFixer/PictureFixer/Client/_Imports.razor"
// using Microsoft.AspNetCore.Components.WebAssembly.Http;

// #line default
// #line hidden
// #nullable disable
// #nullable restore
// #line 8 "/Users/captainsafia/github.com/PictureFixer/PictureFixer/Client/_Imports.razor"
// using Microsoft.JSInterop;

// #line default
// #line hidden
// #nullable disable
// #nullable restore
// #line 9 "/Users/captainsafia/github.com/PictureFixer/PictureFixer/Client/_Imports.razor"
// using PictureFixer.Client;

// #line default
// #line hidden
// #nullable disable
// #nullable restore
// #line 10 "/Users/captainsafia/github.com/PictureFixer/PictureFixer/Client/_Imports.razor"
// using PictureFixer.Client.Shared;

// #line default
// #line hidden
// #nullable disable
// #nullable restore
// #line 11 "/Users/captainsafia/github.com/PictureFixer/PictureFixer/Client/_Imports.razor"
// using PictureFixer.Client.Shared.SectionHelper;

// #line default
// #line hidden
// #nullable disable
// #nullable restore
// #line 12 "/Users/captainsafia/github.com/PictureFixer/PictureFixer/Client/_Imports.razor"
// using PictureFixer.Shared;

// #line default
// #line hidden
// #nullable disable
// #nullable restore
// #line 13 "/Users/captainsafia/github.com/PictureFixer/PictureFixer/Client/_Imports.razor"
// using SixLabors.ImageSharp;

// #line default
// #line hidden
// #nullable disable
// #nullable restore
// #line 14 "/Users/captainsafia/github.com/PictureFixer/PictureFixer/Client/_Imports.razor"
// using SixLabors.ImageSharp.PixelFormats;

// #line default
// #line hidden
// #nullable disable
//     [Microsoft.AspNetCore.Components.RouteAttribute("/")]
//     public partial class Index : Microsoft.AspNetCore.Components.ComponentBase, IDisposable
//     {
//         #pragma warning disable 1998
//         protected override void BuildRenderTree(Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
//         {
//             __Blazor.PictureFixer.Client.Pages.Home.Index.TypeInference.CreateImageList_0(__builder, 0, 1, 
// #nullable restore
// #line 6 "/Users/captainsafia/github.com/PictureFixer/PictureFixer/Client/Pages/Home/Index.razor"
//                    images

// #line default
// #line hidden
// #nullable disable
//             , 2, (context) => (__builder2) => {
//                 __builder2.OpenComponent<PictureFixer.Client.Pages.Home.ImageListItem>(3);
//                 __builder2.AddAttribute(4, "Image", Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<PictureFixer.Shared.EditableImage>(
// #nullable restore
// #line 7 "/Users/captainsafia/github.com/PictureFixer/PictureFixer/Client/Pages/Home/Index.razor"
//                            context

// #line default
// #line hidden
// #nullable disable
//                 ));
//                 __builder2.CloseComponent();
//             }
//             );
//         }
//         #pragma warning restore 1998
// #nullable restore
// #line 10 "/Users/captainsafia/github.com/PictureFixer/PictureFixer/Client/Pages/Home/Index.razor"
       
//     private EditableImage[] images;

//     protected override async Task OnInitializedAsync()
//     {
//         PersistentData.OnPersisting += PersistImageData; // Note: This API will change

//         if (!PersistentData.TryTakeAsJson("preloadedImageData", out images))
//         {
//             images = await Http.GetFromJsonAsync<EditableImage[]>("api/EditableImage");
//         }
//     }

//     private Task PersistImageData()
//     {
//         PersistentData.PersistAsJson("preloadedImageData", images);
//         return Task.CompletedTask;
//     }

//     void IDisposable.Dispose()
//     {
//         PersistentData.OnPersisting -= PersistImageData;
//     }

// #line default
// #line hidden
// #nullable disable
//         [global::Microsoft.AspNetCore.Components.InjectAttribute] private HttpClient Http { get; set; }
//         [global::Microsoft.AspNetCore.Components.InjectAttribute] private ComponentApplicationState PersistentData { get; set; }
//     }
// }
// namespace __Blazor.PictureFixer.Client.Pages.Home.Index
// {
//     #line hidden
//     internal static class TypeInference
//     {
//         public static void CreateImageList_0<TItem>(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder, int seq, int __seq0, global::System.Collections.Generic.IEnumerable<TItem> __arg0, int __seq1, global::Microsoft.AspNetCore.Components.RenderFragment<TItem> __arg1) where TItem : global::PictureFixer.Shared.Image
//         {
//         __builder.OpenComponent<global::PictureFixer.Client.Pages.Home.ImageList<TItem>>(seq);
//         __builder.AddAttribute(__seq0, "Items", __arg0);
//         __builder.AddAttribute(__seq1, "ChildContent", __arg1);
//         __builder.CloseComponent();
//         }
//     }
// }
// #pragma warning restore 1591
